/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetpoo;

/**
 *
 * @author hp
 */
public class ManageRooms extends javax.swing.JFrame {

    /**
     * Creates new form ManageRooms
     */
    public ManageRooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldnumberRooms = new javax.swing.JTextField();
        jTextFieldLName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddroom = new javax.swing.JButton();
        jButtonEditroom = new javax.swing.JButton();
        jButtonRemoveRoom = new javax.swing.JButton();
        jButtonClearFieldsRooms = new javax.swing.JButton();
        jButtonRefreshRooms = new javax.swing.JButton();
        jComboBoxtypechambre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(7, 76, 180));

        jLabel1.setBackground(new java.awt.Color(7, 76, 180));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 44)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Rooms");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 939, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 130, -1, 33));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone N:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 239, -1, -1));
        jPanel1.add(jTextFieldnumberRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 131, 269, 33));
        jPanel1.add(jTextFieldLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 269, 33));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(51, 255, 51));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 130, -1, 330));

        jButtonAddroom.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAddroom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAddroom.setText("Add New Room");
        jPanel1.add(jButtonAddroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 426, -1, 34));

        jButtonEditroom.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEditroom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEditroom.setText("Edit");
        jPanel1.add(jButtonEditroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 426, 115, 34));

        jButtonRemoveRoom.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRemoveRoom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonRemoveRoom.setText("Remove");
        jPanel1.add(jButtonRemoveRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 426, 123, 34));

        jButtonClearFieldsRooms.setBackground(new java.awt.Color(153, 153, 153));
        jButtonClearFieldsRooms.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonClearFieldsRooms.setText("Clear Fields");
        jPanel1.add(jButtonClearFieldsRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 478, 399, 33));

        jButtonRefreshRooms.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRefreshRooms.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonRefreshRooms.setText("Refresh");
        jPanel1.add(jButtonRefreshRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 478, 452, 33));

        jComboBoxtypechambre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jComboBoxtypechambre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chambre simple", "Chambre double ", "Chambre triple ", "Chambre quadruple ", "Suite", " " }));
        jPanel1.add(jComboBoxtypechambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 182, 269, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddroom;
    private javax.swing.JButton jButtonClearFieldsRooms;
    private javax.swing.JButton jButtonEditroom;
    private javax.swing.JButton jButtonRefreshRooms;
    private javax.swing.JButton jButtonRemoveRoom;
    private javax.swing.JComboBox<String> jComboBoxtypechambre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLName;
    private javax.swing.JTextField jTextFieldnumberRooms;
    // End of variables declaration//GEN-END:variables
}
